---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ R_packages }}"

- name: install rstudio rpm key
  become: true
  rpm_key:
    key: "roles/R/files/RPM-GPG-KEY-rstudio"
    state: present
  when: R_rstudio_enabled

- name: install rstudio
  become: true
  yum:
    name: "{{ R_rstudio_package }}"
    state: present
  when: R_rstudio_enabled
