---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ R_packages }}"

- name: install rstudio
  become: true
  yum:
    name: "{{ R_rstudio_package }}"
    state: present
  when: R_rstudio_enabled
