---
- name: install repo key
  become: true
  apt_key:
    url: "{{ postgresql_repo_key }}"
    state: present

- name: install repo
  become: true
  apt_repository:
    repo: "{{ postgresql_repo }}"
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ postgresql_packages }}"
