---
- name: install cloudfoundy repo
  become: true
  yum_repository:
    name: "cloudfoundry"
    description: "Cloud Foundry"
    baseurl: "{{ cloudfoundry_repo_baseurl }}"
    gpgkey: "{{ cloudfoundry_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present

- name: install cf-cli
  become: true
  package:
    name: cf-cli
    state: present
