---
- name: install cloudfoundry repo key
  become: true
  apt_key:
    url: "{{ cloudfoundry_repo_key }}"
    state: present

- name: install cloudfoundry repo
  become: true
  apt_repository:
    repo: "{{ cloudfoundry_repo }}"
    state: present

- name: install cf-cli
  become: true
  package:
    name: cf-cli
    state: present
