---
- name: Verify
  hosts: all
  vars:
    asdf_install_dir: "{{ ansible_env.HOME }}/.asdf"

  tasks:
    - name: load and run asdf
      shell:
        executable: /bin/bash
        cmd: >
          . {{ asdf_install_dir }}/asdf.sh && asdf info
      register: asdf_info

    - name: verify asdf installed
      assert:
        that:
          - asdf_info.stdout | regex_search('ASDF VERSION')
