---
stages:
  - prepare
  - test

variables:
  KITCHEN_YAML: .kitchen-ec2.yml
  GROUP_ID: "sg-0284bddba141545e9"

.test_template: &test_template
  stage: test
  image: "${CI_REGISTRY_IMAGE}/ec2-executor"
  before_script:
    - updatesg -g ${GROUP_ID}
  script:
    - kitchen test ${PLATFORM} -d always
  after_script:
    - kitchen destroy ${PLATFORM}
    - updatesg -r -g ${GROUP_ID}
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Prep Executor:
  stage: prepare
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/tests/Dockerfile.ec2-executor --destination $CI_REGISTRY_IMAGE/ec2-executor
  tags:
    - docker
  only:
    changes:
      - Gemfile*
      - tests/Dockerfile.ec2-executor

Test Ubuntu 18_04:
  <<: *common_test
  variables:
    PLATFORM: ubuntu18

Test CentOS7:
  <<: *common_test
  variables:
    PLATFORM: centos7

Test AmazonLinux2:
  <<: *common_test
  variables:
    PLATFORM: amazonlinux
