---
image: docker:stable

stages:
  - test

services:
  - name: docker:dind

Kitchen Tests:
  stage: test
  script:
    - gem install bundler
    - bundle install
    - kitchen test ubuntu18
  tags:
    - docker
