---
image: chef/chefdk:latest

stages:
  - test

services:
  - name: docker:dind

Kitchen Tests:
  stage: test
  script:
    - apt update
    - apt install -y docker
    - gem install bundler
    - bundle install
    - kitchen test ubuntu18
  tags:
    - docker
