---
stages:
  - prepare
  - test

variables:
  KITCHEN_YAML: .kitchen-ec2.yml

Prep Executor:
  stage: prepare
  image: docker:stable
  services:
    - name: docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}/test-executor" -f Dockerfile.test .
    - docker push "${CI_REGISTRY_IMAGE}/test-executor"
  after_script:
    - docker logout ${CI_REGISTRY}
  only:
    changes:
      - Gemfile*
      - Dockerfile.test

Test Ubuntu 18_04:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/test-executor"
  script:
    - kitchen test ubuntu18 -d always
  after_script:
    - kitchen destroy ubuntu
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test CentOS7:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/test-executor"
  script:
    - kitchen test centos7 -d always
  after_script:
    - kitchen destroy centos7
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test AmazonLinux2:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/test-executor"
  script:
    - kitchen test amazonlinux -d always
  after_script:
    - kitchen destroy amazonlinux
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker
