---
stages:
  - prepare
  - test

variables:
  KITCHEN_YAML: .kitchen-ec2.yml

Prep Executor:
  stage: prepare
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/tests/Dockerfile.ec2-executor --destination $CI_REGISTRY_IMAGE
  tags:
    - docker
  only:
    changes:
      - Gemfile*
      - tests/Dockerfile.ec2-executor

Test Ubuntu 18_04:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/ec2-executor"
  script:
    - curl -sL http://checkip.amazonaws.com
    - kitchen test ubuntu18 -d always
  after_script:
    - kitchen destroy ubuntu
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test CentOS7:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/ec2-executor"
  script:
    - curl -sL http://checkip.amazonaws.com
    - kitchen test centos7 -d always
  after_script:
    - kitchen destroy centos7
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test AmazonLinux2:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/ec2-executor"
  script:
    - curl -sL http://checkip.amazonaws.com
    - kitchen test amazonlinux -d always
  after_script:
    - kitchen destroy amazonlinux
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker
