---
image: registry.gitlab.com/kb9zzw/ansible-test:latest

stages:
  - test

services:
  - name: docker:dind

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

after_script:
  - docker logout ${CI_REGISTRY}

Kitchen Tests:
  stage: test
  script:
    - gem install bundler:1.17.2
    - bundle install
    - ./vendor/bundle/ruby/2.6.5/bin/kitchen test ubuntu18
  tags:
    - docker
