---
image: registry.gitlab.com/kb9zzw/ansible-test:latest

stages:
  - test

services:
  - name: docker:dind

variables:
  - KITCHEN_YAML: .kitchen-docker.yml
  - KITCHEN_TRANSPORT: docker
  - KITCHEN_USE_INTERNAL_NETWORK: 'true'

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

after_script:
  - docker logout ${CI_REGISTRY}

Test Ubuntu 18_04:
  stage: test
  script:
    - bundle install
    - kitchen test ubuntu18 -d always
  artifacts:
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test CentOS7:
  stage: test
  script:
    - bundle install
    - kitchen test centos7 -d always
  artifacts:
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test AmazonLinux2:
  stage: test
  script:
    - docker build -f tests/fixtures/docker/amazonlinux/Dockerfile tests/fixtures/docker/amazonlinux -t amazonlinux:ansible
    - bundle install
    - kitchen test amazonlinux -d always
  artifacts:
    reports:
      junit: reports/test-output.xml
  tags:
    - docker
