---
stages:
  - prepare
  - test

variables:
  KITCHEN_YAML: .kitchen-ec2.yml
  #KITCHEN_TRANSPORT: docker
  #KITCHEN_USE_INTERNAL_NETWORK: 'true'

Prepare Image:
  stage: prepare
  image: docker:stable
  services:
    - name: docker:dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}-test" -f Dockerfile.test .
    - docker push "${CI_REGISTRY_IMAGE}-test"
  after_script:
    - docker logout ${CI_REGISTRY}

Test Ubuntu 18_04:
  stage: test
  image: "${CI_REGISTRY_IMAGE}-test"
  script:
    - kitchen test ubuntu18 -d always
  after_script:
    - kitchen destroy ubuntu
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test CentOS7:
  stage: test
  image: "${CI_REGISTRY_IMAGE}-test"
  script:
    - kitchen test centos7 -d always
  after_script:
    - kitchen destroy centos7
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker

Test AmazonLinux2:
  stage: test
  image: "${CI_REGISTRY_IMAGE}-test"
  script:
    - kitchen test amazonlinux -d always
  after_script:
    - kitchen destroy amazonlinux
  artifacts:
    expire_in: 7d
    reports:
      junit: reports/test-output.xml
  tags:
    - docker
