---
driver:
  name: ec2
  aws_ssh_key_id: id_rsa_gitlab
  security_group_ids: ['sg-0c2b15509b6422523']
  region: us-east-1
  availability_zone: c
  subnet_id: subnet-0a77c1b839ba8a720
  instance_type: t3.medium
  iam_profile_name: test_profile
  associate_public_ip: false
  interface: id
  spot_price: <%= ENV['SPOT_PRICE'] || nil %>

transport:
  ssh_key: <%= ENV['SSH_KEY'] || '~/.ssh/id_rsa_gitlab.pem' %>
  max_ssh_essions: 2
  connection_timeout: 10
  connection_retries: 5

provisioner:
  hosts: workstations
  name: ansible_playbook
  roles_path: roles
  ansible_verbosity: 2
  ansible_verbose: true
  ansible_connection: ssh
  ansible_sudo: false
  playbook: <%= ENV['PLAYBOOK'] || './full.yml' %>

verifier:
  name: inspec
  use_sudo: false
  reporter:
    - cli
    - junit:reports/test-output.xml

platforms:
  - name: ubuntu18
    driver:
      image_search:
        owner-id: 099720109477
        name: ubuntu/images/*/ubuntu-*-18.04*
      transport:
        username: ubuntu
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 20
            delete_on_termination: true

  - name: amazonlinux
    driver:
      image_search:
        owner-alias: amazon
        name: 'amzn2-ami-hvm-2.0.????????.?-x86_64-gp2'
      transport:
        username: ec2-user
      block_device_mappings:
        - device_name: /dev/xvda
          ebs:
            volume_size: 20
            delete_on_termination: true
    lifecycle:
      pre_converge:
        - remote: sudo amazon-linux-extras install -y epel
        - remote: sudo yum install -y ansible

  - name: centos7
    driver:
      image_search:
        owner-id: 679593333241
        name: 'CentOS Linux 7 x86_64 HVM EBS*'
      transport:
        username: centos
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 20
            delete_on_termination: true
      user_data: tests/user_data.sh

suites:
  - name: default
    verifier:
      inspec_tests:
        - tests/roles/base
        - tests/roles/dodpki
        - tests/roles/docker
        - tests/roles/kubernetes
        - tests/roles/python
        - tests/roles/nodejs
        - tests/roles/desktop
        - tests/roles/cloudfoundry
        - tests/roles/anaconda
        - tests/roles/ruby
        - tests/roles/chefdk
        - tests/roles/R
        - tests/roles/postgresql
        - tests/roles/terraform
        - tests/roles/vscode
        - tests/roles/amazonworkspaces
        - tests/roles/dotfiles
