---
driver:
  name: vagrant

provisioner:
  hosts: workstations
  name: ansible_playbook
  roles_path: roles
  ansible_verbosity: 2
  ansible_verbose: true
  ansible_connection: ssh
  ansible_sudo: false
  playbook: <%= ENV['PLAYBOOK'] || './full.yml' %>

verifier:
  name: inspec
  use_sudo: false
  reporter:
    - cli
    - junit:reports/test-output.xml

platforms:
  - name: ubuntu18
    driver:
      box: bento/ubuntu-18.04

  - name: ubuntu20
    driver:
      box: bento/ubuntu-20.04
    provisioner:
      ansible_apt_repo: null

  - name: amazonlinux2
    driver:
      box: bento/amazonlinux-2
    provisioner:
      custom_pre_install_command: sudo amazon-linux-extras install -y epel ansible2

  - name: centos7
    driver:
      box: bento/centos-7.7

  - name: centos8
    driver:
      box: bento/centos-8
    provisioner:
      custom_pre_install_command: >
        sudo dnf install -y epel-release;
        sudo dnf install -y ansible

suites:
  - name: default
    verifier:
      inspec_tests:
        - tests/roles/base
        - tests/roles/dodpki
        - tests/roles/docker
        - tests/roles/podman
        - tests/roles/kubernetes
        - tests/roles/python
        - tests/roles/nodejs
        - tests/roles/desktop
        - tests/roles/cloudfoundry
        - tests/roles/anaconda
        - tests/roles/miniconda
        - tests/roles/ruby
        - tests/roles/chefdk
        - tests/roles/R
        - tests/roles/terraform
        - tests/roles/vscode
        - tests/roles/atom
        - tests/roles/amazonworkspaces
