---
driver:
  name: docker

provisioner:
  hosts: workstations
  name: ansible_playbook
  roles_path: roles
  ansible_verbosity: 2
  ansible_verbose: true
  ansible_connection: ssh
  ansible_sudo: false
  playbook: ./default.yml

verifier:
  name: inspec
  use_sudo: false

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:18.04
  - name: centos
    driver_config:
      image: centos:7
  - name: amazonlinux
    driver_config:
      image: amazonlinux:ansible

suites:
  - name: default
    verifier:
      inspec_tests:
        - tests/roles/base
        - tests/roles/dodpki
        - tests/roles/docker
        - tests/roles/python
