---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ desktop_packages }}"

- name: install amazon linux extras
  become: true
  command:
    cmd: "amazon-linux-extras install -y {{ item }}"
  register: extras
  changed_when: not (extras.stdout | regex_search("already installed"))
  with_items:
    - "{{ desktop_extras }}"
