---
- name: install google chrome repo
  become: true
  yum_repository:
    name: "google-chrome"
    description: "Google Chrome"
    baseurl: "{{ desktop_chrome_repo_baseurl }}"
    gpgkey: "{{ desktop_chrome_repo_gpgkey }}"
    gpgcheck: true
    enabled: "{{desktop_chrome_enabled}}"
    state: present
  when: desktop_chrome_enabled

- name: install chrome
  become: true
  package:
    name: google-chrome-stable
    state: present
  when: desktop_chrome_enabled

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ desktop_packages }}"
