---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ rdev_packages }}"

- name: copy rstudio rpm key
  become: true
  copy:
    src: files/RPM-GPG-KEY-rstudio
    dest: /usr/share/RPM-GPG-KEY-rstudio
    owner: root
    group: root
    mode: 0644
  when: rdev_rstudio_enabled

- name: install rstudio rpm key
  become: true
  rpm_key:
    key: "/usr/share/RPM-GPG-KEY-rstudio"
    state: present
  when: rdev_rstudio_enabled

- name: install rstudio
  become: true
  yum:
    name: "{{ rdev_rstudio_package }}"
    state: present
  when: rdev_rstudio_enabled

- name: include asdf tasks
  include: asdf.yml
