FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive 

ADD Gemfile /Gemfile
ADD Gemfile.lock /Gemfile.lock
ADD tests/session-manager-plugin.deb /session-manager-plugin.deb

RUN apt-get update \
&& apt-get install -y software-properties-common \
&& apt-add-repository --yes ppa:ansible/ansible \
&& apt-get install -y \
    ruby \
    ruby-dev \
    curl \
    python-pip \
    python-setuptools \
    ca-certificates \
    openssl \
    build-essential \
    /session-manager-plugin.deb \
    ansible \
&& pip install awscli \
&& gem install bundler:1.17.2 \
&& bundle install \
&& gem cleanup \
&& apt clean all \
&& rm -rf /usr/lib/ruby/gems/*/cache/* \
          /tmp/* \
          /var/tmp/* \
          /*.deb

ADD tests/ssh_config /root/.ssh/config
