FROM docker:stable

ADD Gemfile /Gemfile
ADD Gemfile.lock /Gemfile.lock

RUN apk update \
&& apk add ruby \
           ruby-etc \
           ruby-bigdecimal \
           ruby-io-console \
           ruby-irb \
           ca-certificates \
           libressl \
           less \
           build-base \
           ruby-dev \
           libressl-dev \
           ansible \
&& gem install bundler:1.17.2 \
&& bundle install \
&& gem cleanup \
&& rm -rf /usr/lib/ruby/gems/*/cache/* \
          /var/cache/apk/* \
          /tmp/* \
          /var/tmp/*

