---
- name: install vscode repo
  become: true
  yum_repository:
    name: 'vscode'
    description: "Visual Studio Code"
    baseurl: "{{ vscode_repo_baseurl }}"
    gpgcheck: true
    gpgkey: "{{ vscode_repo_gpgkey }}"
    enabled: true

- name: install packages
  become: true
  package:
    name: code
    state: present
