---
- name: install vscode repo key
  become: true
  apt_key:
    url: "{{ vscode_repo_key }}"
    state: present

- name: install vscode repo
  become: true
  apt_repository:
    repo: "{{ vscode_repo }}"
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ vscode_packages }}"
