---
- name: install certificates
  become: yes
  copy:
    src: 'certs/'
    dest: '/etc/pki/ca-trust/source/anchors'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'update-ca-trust'
