---
- name: install repo
  become: true
  yum_repository:
    name: "chef"
    description: "Chef"
    baseurl: "{{ chefdk_repo_baseurl }}"
    gpgkey: "{{ chefdk_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present

- name: install chefdk
  become: true
  package:
    name: chefdk
    state: present
