---
- name: get chefdk package
  become: true
  get_url:
    url: "{{ chefdk_package_url }}"
    dest: "{{ chefdk_package_dir }}"
    checksum: "{{ chefdk_checksum }}"
    owner: 'root'
    mode: '0644'

- name: install chefdk
  become: true
  yum:
    name: "{{ chefdk_package_dir}}/{{ chefdk_package }}"
    disable_gpg_check: true
    state: present
