---
miniconda_version: "latest"
miniconda_installer_script: "Miniconda3-{{ miniconda_version }}-Linux-x86_64.sh"
miniconda_installer_url: "https://repo.anaconda.com/miniconda/{{ miniconda_installer_script }}"
miniconda_install_dir: "{{ ansible_env.HOME }}/miniconda3"

miniconda_packages:
  - curl
  - libXcomposite
  - libXcursor
  - libXi
  - libXtst
  - libXrandr
  - alsa-lib
  - mesa-libEGL
  - libXdamage
  - mesa-libGL
  - libXScrnSaver
