---
chefdk_version: "4.7.73"
chefdk_package: "chefdk-{{ chefdk_version }}-1.el7.x86_64.rpm"
chefdk_checksum: "sha256:e4d557bfd6423cf31804219231cf48fc7e78527a12b9e1e43b5e3380e58dc8ce"
chefdk_download_dir: "{{ ansible_env.HOME }}/.downloads"
chefdk_package_url: "https://packages.chef.io/files/stable/chefdk/{{ chefdk_version }}/el/7/chefdk-{{ chefdk_version }}-1.el7.x86_64.rpm"
