---
docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_absent_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_repo_key: 'https://download.docker.com/linux/debian/gpg'
docker_repo_keyring: '/usr/share/keyrings/docker-archive-keyring.gpg'

docker_repo: >-
  deb [arch=amd64 signed-by={{ docker_repo_keyring }}]
  https://download.docker.com/linux/debian
  {{ ansible_distribution_release }}
  stable
