---
docker_repo_baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
docker_repo_gpgkey: "https://download.docker.com/linux/centos/gpg"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_absent_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-engine
