---
- name: install packages
  become: false
  homebrew:
    name: "{{ asdf_packages }}"
    state: present

- name: install asdf
  become: false
  git:
    clone: true
    repo: "{{ asdf_repo_url }}"
    dest: "{{ asdf_install_dir }}"
    version: master

- name: install plugins
  become: false
  shell:
    executable: /bin/zsh
    cmd: >
      . {{ asdf_install_dir }}/asdf.sh && asdf plugin add {{ item }}
  args:
    creates: "{{ asdf_install_dir }}/plugins/{{ item }}"
  with_items:
    - "{{ asdf_plugins }}"
