---
- name: enable epel
  become: true
  command:
    cmd: 'amazon-linux-extras install epel'
    creates: '/etc/yum.repos.d/epel.repo'

- name: install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg

- name: install repo
  become: true
  yum_repository:
    name: kubic
    description: 'kubic libcontainers'
    baseurl: "{{ podman_repo_baseurl }}"
    gpgkey: "{{ podman_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present

- name: install yum-plugin-copr
  become: true
  package:
    name: "yum-plugin-copr"
    state: present

- name: enable lsm5/container-selinux repo
  become: true
  command:
    cmd: 'yum -y copr enable lsm5/container-selinux'
    creates: '/etc/yum.repos.d/_copr_lsm5-container-selinux.repo'
    warn: false

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ podman_packages }}"
