---
- name: install repo
  become: true
  yum_repository:
    name: 'kubic_libcontainers'
    description: "kubic libcontainers"
    baseurl: "{{ podman_repo_baseurl }}"
    gpgcheck: true
    gpgkey: "{{ podman_repo_gpgkey }}"
    enabled: true

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ podman_packages }}"
