---
- name: install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - gnupg

- name: install repo
  become: true
  yum_repository:
    name: kubic
    description: 'kubic libcontainers'
    baseurl: "{{ podman_repo_baseurl }}"
    gpgkey: "{{ podman_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present
  when: podman_enable_kubic_repo

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ podman_packages }}"
