---
- name: install dependencies
  become: true
  apt:
    update_cache: true
    name: gnupg
    state: present

- name: install repo key
  become: true
  apt_key:
    url: "{{ podman_repo_key }}"
    state: present

- name: install repo
  become: true
  apt_repository:
    repo: "{{ podman_repo }}"
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ podman_packages }}"
