---
python_extras:
  - 'python3.8=stable'

python_packages:
  - git
  - tar
  - gzip
  - curl
  - wget
  - make
  - gcc
  - zlib-devel
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel
  - tk-devel
  - libffi-devel
  - xz
  - xz-devel
  - python38
  - python38-devel
