---
anaconda_version: "2020.02"
anaconda_installer_script: "Anaconda3-{{ anaconda_version }}-Linux-x86_64.sh"
anaconda_installer_url: "https://repo.anaconda.com/archive/{{ anaconda_installer_script }}"
anaconda_install_dir: "{{ ansible_env.HOME }}/anaconda3"

anaconda_packages:
  - curl
  - libXcomposite
  - libXcursor
  - libXi
  - libXtst
  - libXrandr
  - alsa-lib
  - mesa-libEGL
  - libXdamage
  - mesa-libGL
  - libXScrnSaver
