---
- name: 'install atom repository key'
  become: true
  apt_key:
    url: "{{ atom_key }}"
    state: present
  vars:
    atom_key: 'https://packagecloud.io/AtomEditor/atom/gpgkey'

- name: 'install atom repository'
  become: true
  apt_repository:
    repo: "deb {{ atom_repo }} any main"
    state: present
  vars:
    atom_repo: 'https://packagecloud.io/AtomEditor/atom/any/'

- name: 'install atom'
  become: true
  package:
    name: 'atom'
    state: present
