---
- name: install repo
  become: true
  yum_repository:
    name: "kubernetes"
    description: "Kubernetes"
    baseurl: "{{ kubernetes_repo_baseurl }}"
    gpgkey: "{{ kubernetes_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ kubernetes_packages }}"
