---
- name: install repo key
  become: true
  apt_key:
    url: "{{ kubernetes_repo_key }}"
    state: present

- name: install repo
  become: true
  apt_repository:
    repo: "{{ kubernetes_repo }}"
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ kubernetes_packages }}"
