---
- name: check for asdf
  stat:
    path: "{{ ansible_env.HOME }}/.asdf"
  register: asdf

- name: install asdf java plugin
  shell: |
    . {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf plugin add java
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/java"
  when: asdf.stat.exists

- name: install versions
  become: false
  shell: |
    . {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf install java {{ item }}
  args:
    executable: /bin/bash
  register: asdf_install
  changed_when: '"is already installed" not in asdf_install.stdout'
  with_items:
    - "{{ java_versions }}"
  when: asdf.stat.exists

- name: set global version
  become: false
  shell: |
    . {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf global java {{ java_global_version }}
  args:
    executable: /bin/bash
  changed_when: false
  when: asdf.stat.exists and java_global_version
