---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ java_packages }}"

- name: install sdkman
  become: false
  shell: >
    {{ java_sdkman_script }}
  args:
    creates: "{{ ansible_env.HOME }}/.sdkman"
    warn: false
