---
- name: include variables
  include_vars: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "defaults/{{ platform }}-{{ version }}.yml"
      - "defaults/{{ platform }}.yml"
      - defaults/none.yml

- name: include tasks
  include: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "{{ platform }}-{{ version }}.yml"
      - "{{ platform }}.yml"
      - unsupported.yml
