---
- name: install dependencies
  become: true
  package:
    name: gnupg
    state: present

- name: install repo
  become: true
  yum_repository:
    name: "virtualbox"
    description: "Oracle Virtualbox"
    baseurl: "{{ virtualbox_repo_baseurl }}"
    gpgkey: "{{ virtualbox_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present

- name: install virtualbox
  become: true
  package:
    name: "{{ virtualbox_package }}"
    state: present
