---
- name: install prerequisites
  become: true
  package:
    name: unzip
    state: present

- name: ensure install dir exists
  become: false
  file:
    name: "{{ terraform_install_dir }}"
    state: directory
    mode: '0755'

- name: install terraform
  become: false
  unarchive:
    src: "{{ terraform_url }}"
    dest: "{{ terraform_install_dir }}"
    remote_src: true
