---
- name: get anaconda installer
  become: false
  get_url:
    url: "{{ anaconda_installer_url }}"
    dest: "{{ anaconda_installer_dest }}"
    owner: "{{ ansible_user_id }}"
    mode: '0755'

- name: install anaconda
  become: false
  command:
    cmd: "{{ anaconda_installer_dest }} -b -p {{ anaconda_install_dir }}"
    creates: "{{ anaconda_install_dir }}"
