---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ anaconda_packages }}"

- name: add installer script
  become: false
  template:
    src: install_anaconda.j2
    dest: "{{ ansible_env.HOME }}/.install_anaconda"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: install anaconda
  become: false
  command: "{{ ansible_env.HOME }}/.install_anaconda"
  args:
    creates: "{{ anaconda_install_dir }}"
