---
- name: Converge
  hosts: all
  vars:
    python_versions:
      - 3.8.8
    python_global_version: 3.8.8

  tasks:
    - name: "Include asdf"
      include_role:
        name: "asdf"

    - name: "Include python"
      include_role:
        name: "python"
