---
- name: Converge
  hosts: all
  vars:
    java_versions:
      - openjdk-16
    java_global_version: openjdk-16

  tasks:
    - name: "Include asdf"
      include_role:
        name: "asdf"

    - name: "Include java"
      include_role:
        name: "java"
