---
- name: remove older docker
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ docker_absent_packages }}"

- name: install docker repo
  become: true
  yum_repository:
    name: docker-ce
    description: 'Docker CE'
    baseurl: "{{ docker_repo_baseurl }}"
    gpgkey: "{{ docker_repo_gpgkey }}"
    gpgcheck: true
    enabled: true
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"
  notify: "restart docker"

- name: create docker group
  become: true
  group:
    name: docker
    state: present

- name: append users to docker group
  become: true
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: true
  with_items:
    - "{{ docker_users }}"

- name: install docker-compose
  become: true
  shell: >
    {{ docker_compose_script }}
  args:
    creates: '/usr/bin/docker-compose'
    warn: false
