---
- name: 'install docker repository key'
  become: true
  apt_key:
    url: "{{ docker_key }}"
    state: present
  vars:
    docker_key: 'https://download.docker.com/linux/ubuntu/gpg'

- name: 'install docker repository'
  become: true
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo }} bionic stable edge"
    state: present
  vars:
    docker_repo: 'https://download.docker.com/linux/ubuntu'

- name: 'install docker'
  become: true
  package:
    name: 'docker-ce'
    state: present
