---
- name: install docker repo gpgkey
  become: true
  apt_key:
    id: "{{ docker_repo_id }}"
    url: "{{ docker_repo_key }}"
    state: present

- name: install docker repo
  become: true
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"

- name: create docker group
  become: true
  group:
    name: docker
    state: present

- name: append users to docker group
  become: true
  user:
    name: "{{ item }}"
    groups:
      - docker
    append: true
  with_items:
    - "{{ docker_users }}"
