---
- name: enable epel
  become: yes
  command:
    cmd: 'amazon-linux-extras install epel'
    creates: '/etc/yum.repos.d/epel.repo'

- name: install packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ base_packages }}"
