---
- name: install base packages
  become: false
  homebrew:
    name: "{{ base_packages }}"
    state: present

- name: install casks
  become: false
  homebrew_cask:
    name: "{{ base_casks }}"
    state: present
