---
- debug:
    msg: "{{ ansible_user_id }}"

- name: include variables
  include_vars: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "defaults/{{ platform }}.yml"
      - defaults/none.yml

- name: include tasks
  include: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "{{ platform }}.yml"
      - unsupported.yml
