---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ miniconda_packages }}"

- name: add installer script
  become: false
  template:
    src: install_miniconda.j2
    dest: "{{ ansible_env.HOME }}/.install_miniconda"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: install miniconda
  become: false
  command: "{{ ansible_env.HOME }}/.install_miniconda"
  args:
    creates: "{{ miniconda_install_dir }}"
