---
- name: install asdf {{ asdf_app }} plugin
  shell: |
    . {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf plugin add {{ asdf_app }}
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.asdf/plugins/{{ asdf_app }}"

- name: install versions
  become: false
  shell: |
    . {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf install {{ asdf_app }} {{ item }}
  args:
    executable: /bin/bash
  register: asdf_install
  changed_when: '"is already installed" not in asdf_install.stdout'
  with_items:
    - '{{vars["asdf_app"]_versions }}'

- name: set global version
  become: false
  shell: |
    . {{ ansible_env.HOME }}/.asdf/asdf.sh
    asdf global {{ asdf_app }} {{ vars["asdf_app"]_global_version }}
  args:
    executable: /bin/bash
  changed_when: false
  when: '{{ asdf_app }}_global_version != None'
