---
- name: include variables
  include_vars: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "defaults/{{ platform }}.yml"
      - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "defaults/{{ ansible_distribution }}.yml"
      - defaults/none.yml

- name: include tasks
  include: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "{{ platform }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - unsupported.yml
