---
- name: install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ruby_packages }}"

- name: install rbenv
  become: false
  shell: >
    {{ ruby_rbenv_script }}
  args:
    creates: "{{ ruby_rbenv_dir }}"
